{
 "title": "Network",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DNS Server Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_HOSTNAME",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "HOSTNAME" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DNS",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_HOSTNAME > $tag_DNSSERVER#$tag_DNSPORT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "DNSSERVER" ], "type": "tag" },
      { "params": [ "HOSTNAME" ], "type": "tag" },
      { "params": [ "DNSPORT" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "DNSSTATUS",
     "select": [
      [
       { "params": [ "querytime" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Historic Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_HOSTNAME",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "HOSTNAME" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DNS",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_MSG $tag_HOSTNAME",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "HOSTNAME" ], "type": "tag" },
      { "params": [ "MSG" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "DNSALERT",
     "select": [
      [
       { "params": [ "alert" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}